version: "3.8"
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - PORT=8000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - "80:8000"
    worker:
        build:
            context: ./
            dockerfile: Dockerfile
        command: rq worker --url redis://redis:6379


        
